name = "dummrum"
main = "dist/_worker.js/index.js"
compatibility_date = "2026-03-17"
compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = true

[assets]
binding = "ASSETS"
directory = "./dist"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "rmv-departures"
database_id = "6db89bbe-ac67-4d65-864e-5c6b19150a28"
