name = "dummrum"
main = "./src/worker.ts"
compatibility_date = "2026-03-17"
compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = true

[triggers]
crons = ["*/3 * * * *"]

[assets]
binding = "ASSETS"
directory = "./dist"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "SESSION"
id = "1c4a4871e4be414e8dbd3eac7973f8ae"

[[d1_databases]]
binding = "DB"
database_name = "rmv-departures"
database_id = "6db89bbe-ac67-4d65-864e-5c6b19150a28"
migrations_dir = "migrations"
