/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangStationRouteRouteImport } from './routes/$lang/$station/route'
import { Route as LangStationIndexRouteImport } from './routes/$lang/$station/index'
import { Route as LangOperatorOperatorIndexRouteImport } from './routes/$lang/operator/$operator/index'
import { Route as LangLineLineIndexRouteImport } from './routes/$lang/line/$line/index'
import { Route as LangStationDayDateRouteImport } from './routes/$lang/$station/day/$date'
import { Route as LangOperatorOperatorDayDateRouteImport } from './routes/$lang/operator/$operator/day/$date'
import { Route as LangLineLineDayDateRouteImport } from './routes/$lang/line/$line/day/$date'

const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangStationRouteRoute = LangStationRouteRouteImport.update({
  id: '/$station',
  path: '/$station',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangStationIndexRoute = LangStationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangStationRouteRoute,
} as any)
const LangOperatorOperatorIndexRoute =
  LangOperatorOperatorIndexRouteImport.update({
    id: '/operator/$operator/',
    path: '/operator/$operator/',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangLineLineIndexRoute = LangLineLineIndexRouteImport.update({
  id: '/line/$line/',
  path: '/line/$line/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangStationDayDateRoute = LangStationDayDateRouteImport.update({
  id: '/day/$date',
  path: '/day/$date',
  getParentRoute: () => LangStationRouteRoute,
} as any)
const LangOperatorOperatorDayDateRoute =
  LangOperatorOperatorDayDateRouteImport.update({
    id: '/operator/$operator/day/$date',
    path: '/operator/$operator/day/$date',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangLineLineDayDateRoute = LangLineLineDayDateRouteImport.update({
  id: '/line/$line/day/$date',
  path: '/line/$line/day/$date',
  getParentRoute: () => LangRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/$station': typeof LangStationRouteRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/$station/': typeof LangStationIndexRoute
  '/$lang/$station/day/$date': typeof LangStationDayDateRoute
  '/$lang/line/$line/': typeof LangLineLineIndexRoute
  '/$lang/operator/$operator/': typeof LangOperatorOperatorIndexRoute
  '/$lang/line/$line/day/$date': typeof LangLineLineDayDateRoute
  '/$lang/operator/$operator/day/$date': typeof LangOperatorOperatorDayDateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/$station': typeof LangStationIndexRoute
  '/$lang/$station/day/$date': typeof LangStationDayDateRoute
  '/$lang/line/$line': typeof LangLineLineIndexRoute
  '/$lang/operator/$operator': typeof LangOperatorOperatorIndexRoute
  '/$lang/line/$line/day/$date': typeof LangLineLineDayDateRoute
  '/$lang/operator/$operator/day/$date': typeof LangOperatorOperatorDayDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/$station': typeof LangStationRouteRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/$station/': typeof LangStationIndexRoute
  '/$lang/$station/day/$date': typeof LangStationDayDateRoute
  '/$lang/line/$line/': typeof LangLineLineIndexRoute
  '/$lang/operator/$operator/': typeof LangOperatorOperatorIndexRoute
  '/$lang/line/$line/day/$date': typeof LangLineLineDayDateRoute
  '/$lang/operator/$operator/day/$date': typeof LangOperatorOperatorDayDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/$station'
    | '/$lang/'
    | '/$lang/$station/'
    | '/$lang/$station/day/$date'
    | '/$lang/line/$line/'
    | '/$lang/operator/$operator/'
    | '/$lang/line/$line/day/$date'
    | '/$lang/operator/$operator/day/$date'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/$lang/$station'
    | '/$lang/$station/day/$date'
    | '/$lang/line/$line'
    | '/$lang/operator/$operator'
    | '/$lang/line/$line/day/$date'
    | '/$lang/operator/$operator/day/$date'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/$station'
    | '/$lang/'
    | '/$lang/$station/'
    | '/$lang/$station/day/$date'
    | '/$lang/line/$line/'
    | '/$lang/operator/$operator/'
    | '/$lang/line/$line/day/$date'
    | '/$lang/operator/$operator/day/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/$station': {
      id: '/$lang/$station'
      path: '/$station'
      fullPath: '/$lang/$station'
      preLoaderRoute: typeof LangStationRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/$station/': {
      id: '/$lang/$station/'
      path: '/'
      fullPath: '/$lang/$station/'
      preLoaderRoute: typeof LangStationIndexRouteImport
      parentRoute: typeof LangStationRouteRoute
    }
    '/$lang/operator/$operator/': {
      id: '/$lang/operator/$operator/'
      path: '/operator/$operator'
      fullPath: '/$lang/operator/$operator/'
      preLoaderRoute: typeof LangOperatorOperatorIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/line/$line/': {
      id: '/$lang/line/$line/'
      path: '/line/$line'
      fullPath: '/$lang/line/$line/'
      preLoaderRoute: typeof LangLineLineIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/$station/day/$date': {
      id: '/$lang/$station/day/$date'
      path: '/day/$date'
      fullPath: '/$lang/$station/day/$date'
      preLoaderRoute: typeof LangStationDayDateRouteImport
      parentRoute: typeof LangStationRouteRoute
    }
    '/$lang/operator/$operator/day/$date': {
      id: '/$lang/operator/$operator/day/$date'
      path: '/operator/$operator/day/$date'
      fullPath: '/$lang/operator/$operator/day/$date'
      preLoaderRoute: typeof LangOperatorOperatorDayDateRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/line/$line/day/$date': {
      id: '/$lang/line/$line/day/$date'
      path: '/line/$line/day/$date'
      fullPath: '/$lang/line/$line/day/$date'
      preLoaderRoute: typeof LangLineLineDayDateRouteImport
      parentRoute: typeof LangRouteRoute
    }
  }
}

interface LangStationRouteRouteChildren {
  LangStationIndexRoute: typeof LangStationIndexRoute
  LangStationDayDateRoute: typeof LangStationDayDateRoute
}

const LangStationRouteRouteChildren: LangStationRouteRouteChildren = {
  LangStationIndexRoute: LangStationIndexRoute,
  LangStationDayDateRoute: LangStationDayDateRoute,
}

const LangStationRouteRouteWithChildren =
  LangStationRouteRoute._addFileChildren(LangStationRouteRouteChildren)

interface LangRouteRouteChildren {
  LangStationRouteRoute: typeof LangStationRouteRouteWithChildren
  LangIndexRoute: typeof LangIndexRoute
  LangLineLineIndexRoute: typeof LangLineLineIndexRoute
  LangOperatorOperatorIndexRoute: typeof LangOperatorOperatorIndexRoute
  LangLineLineDayDateRoute: typeof LangLineLineDayDateRoute
  LangOperatorOperatorDayDateRoute: typeof LangOperatorOperatorDayDateRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangStationRouteRoute: LangStationRouteRouteWithChildren,
  LangIndexRoute: LangIndexRoute,
  LangLineLineIndexRoute: LangLineLineIndexRoute,
  LangOperatorOperatorIndexRoute: LangOperatorOperatorIndexRoute,
  LangLineLineDayDateRoute: LangLineLineDayDateRoute,
  LangOperatorOperatorDayDateRoute: LangOperatorOperatorDayDateRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
