/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LangSplatRouteImport } from "./routes/$lang/$";
import { Route as LangStationDayDateRouteImport } from "./routes/$lang/$station/day/$date";
import { Route as LangStationIndexRouteImport } from "./routes/$lang/$station/index";
import { Route as LangStationRouteRouteImport } from "./routes/$lang/$station/route";
import { Route as LangIndexRouteImport } from "./routes/$lang/index";
import { Route as LangLineLineDayDateRouteImport } from "./routes/$lang/line/$line/day/$date";
import { Route as LangLineLineIndexRouteImport } from "./routes/$lang/line/$line/index";
import { Route as LangMapIndexRouteImport } from "./routes/$lang/map/index";
import { Route as LangOperatorOperatorDayDateRouteImport } from "./routes/$lang/operator/$operator/day/$date";
import { Route as LangOperatorOperatorIndexRouteImport } from "./routes/$lang/operator/$operator/index";
import { Route as LangRouteRouteImport } from "./routes/$lang/route";
import { Route as ApiFerryVehiclesRouteImport } from "./routes/api/ferry/vehicles";
import { Route as ApiFlixRouteUuidRouteImport } from "./routes/api/flix/route/$uuid";
import { Route as ApiFlixVehiclesRouteImport } from "./routes/api/flix/vehicles";
import { Route as ApiPickerDirectionsRouteImport } from "./routes/api/picker/directions";
import { Route as ApiPickerLinesRouteImport } from "./routes/api/picker/lines";
import { Route as ApiPickerStopsRouteImport } from "./routes/api/picker/stops";
import { Route as IndexRouteImport } from "./routes/index";

const LangRouteRoute = LangRouteRouteImport.update({
	id: "/$lang",
	path: "/$lang",
	getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRouteImport,
} as any);
const LangIndexRoute = LangIndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => LangRouteRoute,
} as any);
const LangSplatRoute = LangSplatRouteImport.update({
	id: "/$",
	path: "/$",
	getParentRoute: () => LangRouteRoute,
} as any);
const LangStationRouteRoute = LangStationRouteRouteImport.update({
	id: "/$station",
	path: "/$station",
	getParentRoute: () => LangRouteRoute,
} as any);
const LangMapIndexRoute = LangMapIndexRouteImport.update({
	id: "/map/",
	path: "/map/",
	getParentRoute: () => LangRouteRoute,
} as any);
const LangStationIndexRoute = LangStationIndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => LangStationRouteRoute,
} as any);
const ApiPickerStopsRoute = ApiPickerStopsRouteImport.update({
	id: "/api/picker/stops",
	path: "/api/picker/stops",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiPickerLinesRoute = ApiPickerLinesRouteImport.update({
	id: "/api/picker/lines",
	path: "/api/picker/lines",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiPickerDirectionsRoute = ApiPickerDirectionsRouteImport.update({
	id: "/api/picker/directions",
	path: "/api/picker/directions",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiFlixVehiclesRoute = ApiFlixVehiclesRouteImport.update({
	id: "/api/flix/vehicles",
	path: "/api/flix/vehicles",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiFerryVehiclesRoute = ApiFerryVehiclesRouteImport.update({
	id: "/api/ferry/vehicles",
	path: "/api/ferry/vehicles",
	getParentRoute: () => rootRouteImport,
} as any);
const LangOperatorOperatorIndexRoute =
	LangOperatorOperatorIndexRouteImport.update({
		id: "/operator/$operator/",
		path: "/operator/$operator/",
		getParentRoute: () => LangRouteRoute,
	} as any);
const LangLineLineIndexRoute = LangLineLineIndexRouteImport.update({
	id: "/line/$line/",
	path: "/line/$line/",
	getParentRoute: () => LangRouteRoute,
} as any);
const ApiFlixRouteUuidRoute = ApiFlixRouteUuidRouteImport.update({
	id: "/api/flix/route/$uuid",
	path: "/api/flix/route/$uuid",
	getParentRoute: () => rootRouteImport,
} as any);
const LangStationDayDateRoute = LangStationDayDateRouteImport.update({
	id: "/day/$date",
	path: "/day/$date",
	getParentRoute: () => LangStationRouteRoute,
} as any);
const LangOperatorOperatorDayDateRoute =
	LangOperatorOperatorDayDateRouteImport.update({
		id: "/operator/$operator/day/$date",
		path: "/operator/$operator/day/$date",
		getParentRoute: () => LangRouteRoute,
	} as any);
const LangLineLineDayDateRoute = LangLineLineDayDateRouteImport.update({
	id: "/line/$line/day/$date",
	path: "/line/$line/day/$date",
	getParentRoute: () => LangRouteRoute,
} as any);

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/$lang": typeof LangRouteRouteWithChildren;
	"/$lang/$station": typeof LangStationRouteRouteWithChildren;
	"/$lang/$": typeof LangSplatRoute;
	"/$lang/": typeof LangIndexRoute;
	"/api/ferry/vehicles": typeof ApiFerryVehiclesRoute;
	"/api/flix/vehicles": typeof ApiFlixVehiclesRoute;
	"/api/picker/directions": typeof ApiPickerDirectionsRoute;
	"/api/picker/lines": typeof ApiPickerLinesRoute;
	"/api/picker/stops": typeof ApiPickerStopsRoute;
	"/$lang/$station/": typeof LangStationIndexRoute;
	"/$lang/map/": typeof LangMapIndexRoute;
	"/$lang/$station/day/$date": typeof LangStationDayDateRoute;
	"/api/flix/route/$uuid": typeof ApiFlixRouteUuidRoute;
	"/$lang/line/$line/": typeof LangLineLineIndexRoute;
	"/$lang/operator/$operator/": typeof LangOperatorOperatorIndexRoute;
	"/$lang/line/$line/day/$date": typeof LangLineLineDayDateRoute;
	"/$lang/operator/$operator/day/$date": typeof LangOperatorOperatorDayDateRoute;
}
export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/$lang/$": typeof LangSplatRoute;
	"/$lang": typeof LangIndexRoute;
	"/api/ferry/vehicles": typeof ApiFerryVehiclesRoute;
	"/api/flix/vehicles": typeof ApiFlixVehiclesRoute;
	"/api/picker/directions": typeof ApiPickerDirectionsRoute;
	"/api/picker/lines": typeof ApiPickerLinesRoute;
	"/api/picker/stops": typeof ApiPickerStopsRoute;
	"/$lang/$station": typeof LangStationIndexRoute;
	"/$lang/map": typeof LangMapIndexRoute;
	"/$lang/$station/day/$date": typeof LangStationDayDateRoute;
	"/api/flix/route/$uuid": typeof ApiFlixRouteUuidRoute;
	"/$lang/line/$line": typeof LangLineLineIndexRoute;
	"/$lang/operator/$operator": typeof LangOperatorOperatorIndexRoute;
	"/$lang/line/$line/day/$date": typeof LangLineLineDayDateRoute;
	"/$lang/operator/$operator/day/$date": typeof LangOperatorOperatorDayDateRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/": typeof IndexRoute;
	"/$lang": typeof LangRouteRouteWithChildren;
	"/$lang/$station": typeof LangStationRouteRouteWithChildren;
	"/$lang/$": typeof LangSplatRoute;
	"/$lang/": typeof LangIndexRoute;
	"/api/ferry/vehicles": typeof ApiFerryVehiclesRoute;
	"/api/flix/vehicles": typeof ApiFlixVehiclesRoute;
	"/api/picker/directions": typeof ApiPickerDirectionsRoute;
	"/api/picker/lines": typeof ApiPickerLinesRoute;
	"/api/picker/stops": typeof ApiPickerStopsRoute;
	"/$lang/$station/": typeof LangStationIndexRoute;
	"/$lang/map/": typeof LangMapIndexRoute;
	"/$lang/$station/day/$date": typeof LangStationDayDateRoute;
	"/api/flix/route/$uuid": typeof ApiFlixRouteUuidRoute;
	"/$lang/line/$line/": typeof LangLineLineIndexRoute;
	"/$lang/operator/$operator/": typeof LangOperatorOperatorIndexRoute;
	"/$lang/line/$line/day/$date": typeof LangLineLineDayDateRoute;
	"/$lang/operator/$operator/day/$date": typeof LangOperatorOperatorDayDateRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths:
		| "/"
		| "/$lang"
		| "/$lang/$station"
		| "/$lang/$"
		| "/$lang/"
		| "/api/ferry/vehicles"
		| "/api/flix/vehicles"
		| "/api/picker/directions"
		| "/api/picker/lines"
		| "/api/picker/stops"
		| "/$lang/$station/"
		| "/$lang/map/"
		| "/$lang/$station/day/$date"
		| "/api/flix/route/$uuid"
		| "/$lang/line/$line/"
		| "/$lang/operator/$operator/"
		| "/$lang/line/$line/day/$date"
		| "/$lang/operator/$operator/day/$date";
	fileRoutesByTo: FileRoutesByTo;
	to:
		| "/"
		| "/$lang/$"
		| "/$lang"
		| "/api/ferry/vehicles"
		| "/api/flix/vehicles"
		| "/api/picker/directions"
		| "/api/picker/lines"
		| "/api/picker/stops"
		| "/$lang/$station"
		| "/$lang/map"
		| "/$lang/$station/day/$date"
		| "/api/flix/route/$uuid"
		| "/$lang/line/$line"
		| "/$lang/operator/$operator"
		| "/$lang/line/$line/day/$date"
		| "/$lang/operator/$operator/day/$date";
	id:
		| "__root__"
		| "/"
		| "/$lang"
		| "/$lang/$station"
		| "/$lang/$"
		| "/$lang/"
		| "/api/ferry/vehicles"
		| "/api/flix/vehicles"
		| "/api/picker/directions"
		| "/api/picker/lines"
		| "/api/picker/stops"
		| "/$lang/$station/"
		| "/$lang/map/"
		| "/$lang/$station/day/$date"
		| "/api/flix/route/$uuid"
		| "/$lang/line/$line/"
		| "/$lang/operator/$operator/"
		| "/$lang/line/$line/day/$date"
		| "/$lang/operator/$operator/day/$date";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	LangRouteRoute: typeof LangRouteRouteWithChildren;
	ApiFerryVehiclesRoute: typeof ApiFerryVehiclesRoute;
	ApiFlixVehiclesRoute: typeof ApiFlixVehiclesRoute;
	ApiPickerDirectionsRoute: typeof ApiPickerDirectionsRoute;
	ApiPickerLinesRoute: typeof ApiPickerLinesRoute;
	ApiPickerStopsRoute: typeof ApiPickerStopsRoute;
	ApiFlixRouteUuidRoute: typeof ApiFlixRouteUuidRoute;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/$lang": {
			id: "/$lang";
			path: "/$lang";
			fullPath: "/$lang";
			preLoaderRoute: typeof LangRouteRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/$lang/": {
			id: "/$lang/";
			path: "/";
			fullPath: "/$lang/";
			preLoaderRoute: typeof LangIndexRouteImport;
			parentRoute: typeof LangRouteRoute;
		};
		"/$lang/$": {
			id: "/$lang/$";
			path: "/$";
			fullPath: "/$lang/$";
			preLoaderRoute: typeof LangSplatRouteImport;
			parentRoute: typeof LangRouteRoute;
		};
		"/$lang/$station": {
			id: "/$lang/$station";
			path: "/$station";
			fullPath: "/$lang/$station";
			preLoaderRoute: typeof LangStationRouteRouteImport;
			parentRoute: typeof LangRouteRoute;
		};
		"/$lang/map/": {
			id: "/$lang/map/";
			path: "/map";
			fullPath: "/$lang/map/";
			preLoaderRoute: typeof LangMapIndexRouteImport;
			parentRoute: typeof LangRouteRoute;
		};
		"/$lang/$station/": {
			id: "/$lang/$station/";
			path: "/";
			fullPath: "/$lang/$station/";
			preLoaderRoute: typeof LangStationIndexRouteImport;
			parentRoute: typeof LangStationRouteRoute;
		};
		"/api/picker/stops": {
			id: "/api/picker/stops";
			path: "/api/picker/stops";
			fullPath: "/api/picker/stops";
			preLoaderRoute: typeof ApiPickerStopsRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/picker/lines": {
			id: "/api/picker/lines";
			path: "/api/picker/lines";
			fullPath: "/api/picker/lines";
			preLoaderRoute: typeof ApiPickerLinesRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/picker/directions": {
			id: "/api/picker/directions";
			path: "/api/picker/directions";
			fullPath: "/api/picker/directions";
			preLoaderRoute: typeof ApiPickerDirectionsRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/flix/vehicles": {
			id: "/api/flix/vehicles";
			path: "/api/flix/vehicles";
			fullPath: "/api/flix/vehicles";
			preLoaderRoute: typeof ApiFlixVehiclesRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/ferry/vehicles": {
			id: "/api/ferry/vehicles";
			path: "/api/ferry/vehicles";
			fullPath: "/api/ferry/vehicles";
			preLoaderRoute: typeof ApiFerryVehiclesRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/$lang/operator/$operator/": {
			id: "/$lang/operator/$operator/";
			path: "/operator/$operator";
			fullPath: "/$lang/operator/$operator/";
			preLoaderRoute: typeof LangOperatorOperatorIndexRouteImport;
			parentRoute: typeof LangRouteRoute;
		};
		"/$lang/line/$line/": {
			id: "/$lang/line/$line/";
			path: "/line/$line";
			fullPath: "/$lang/line/$line/";
			preLoaderRoute: typeof LangLineLineIndexRouteImport;
			parentRoute: typeof LangRouteRoute;
		};
		"/api/flix/route/$uuid": {
			id: "/api/flix/route/$uuid";
			path: "/api/flix/route/$uuid";
			fullPath: "/api/flix/route/$uuid";
			preLoaderRoute: typeof ApiFlixRouteUuidRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/$lang/$station/day/$date": {
			id: "/$lang/$station/day/$date";
			path: "/day/$date";
			fullPath: "/$lang/$station/day/$date";
			preLoaderRoute: typeof LangStationDayDateRouteImport;
			parentRoute: typeof LangStationRouteRoute;
		};
		"/$lang/operator/$operator/day/$date": {
			id: "/$lang/operator/$operator/day/$date";
			path: "/operator/$operator/day/$date";
			fullPath: "/$lang/operator/$operator/day/$date";
			preLoaderRoute: typeof LangOperatorOperatorDayDateRouteImport;
			parentRoute: typeof LangRouteRoute;
		};
		"/$lang/line/$line/day/$date": {
			id: "/$lang/line/$line/day/$date";
			path: "/line/$line/day/$date";
			fullPath: "/$lang/line/$line/day/$date";
			preLoaderRoute: typeof LangLineLineDayDateRouteImport;
			parentRoute: typeof LangRouteRoute;
		};
	}
}

interface LangStationRouteRouteChildren {
	LangStationIndexRoute: typeof LangStationIndexRoute;
	LangStationDayDateRoute: typeof LangStationDayDateRoute;
}

const LangStationRouteRouteChildren: LangStationRouteRouteChildren = {
	LangStationIndexRoute: LangStationIndexRoute,
	LangStationDayDateRoute: LangStationDayDateRoute,
};

const LangStationRouteRouteWithChildren =
	LangStationRouteRoute._addFileChildren(LangStationRouteRouteChildren);

interface LangRouteRouteChildren {
	LangStationRouteRoute: typeof LangStationRouteRouteWithChildren;
	LangSplatRoute: typeof LangSplatRoute;
	LangIndexRoute: typeof LangIndexRoute;
	LangMapIndexRoute: typeof LangMapIndexRoute;
	LangLineLineIndexRoute: typeof LangLineLineIndexRoute;
	LangOperatorOperatorIndexRoute: typeof LangOperatorOperatorIndexRoute;
	LangLineLineDayDateRoute: typeof LangLineLineDayDateRoute;
	LangOperatorOperatorDayDateRoute: typeof LangOperatorOperatorDayDateRoute;
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
	LangStationRouteRoute: LangStationRouteRouteWithChildren,
	LangSplatRoute: LangSplatRoute,
	LangIndexRoute: LangIndexRoute,
	LangMapIndexRoute: LangMapIndexRoute,
	LangLineLineIndexRoute: LangLineLineIndexRoute,
	LangOperatorOperatorIndexRoute: LangOperatorOperatorIndexRoute,
	LangLineLineDayDateRoute: LangLineLineDayDateRoute,
	LangOperatorOperatorDayDateRoute: LangOperatorOperatorDayDateRoute,
};

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
	LangRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	LangRouteRoute: LangRouteRouteWithChildren,
	ApiFerryVehiclesRoute: ApiFerryVehiclesRoute,
	ApiFlixVehiclesRoute: ApiFlixVehiclesRoute,
	ApiPickerDirectionsRoute: ApiPickerDirectionsRoute,
	ApiPickerLinesRoute: ApiPickerLinesRoute,
	ApiPickerStopsRoute: ApiPickerStopsRoute,
	ApiFlixRouteUuidRoute: ApiFlixRouteUuidRoute,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

import type { createStart } from "@tanstack/react-start";
import type { getRouter } from "./router.tsx";

declare module "@tanstack/react-start" {
	interface Register {
		ssr: true;
		router: Awaited<ReturnType<typeof getRouter>>;
	}
}
